# create your drupal and postgres config here, based off the last assignment

services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: api
      POSTGRES_DB: api
    volumes:
      - postgres-db:/var/lib/postgresql/data

  node-app:
    build:
      context: .
      dockerfile: nodeApp.Dockerfile
    env_file:
      - .env
    ports:
      - 8081:4001
    depends_on:
      - postgres

volumes:
  postgres-db:
